# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(250, 320)
        self.name = QtWidgets.QLineEdit(Dialog)
        self.name.setGeometry(QtCore.QRect(130, 10, 113, 20))
        self.name.setObjectName("name")
        self.obzharka = QtWidgets.QLineEdit(Dialog)
        self.obzharka.setGeometry(QtCore.QRect(130, 40, 113, 20))
        self.obzharka.setObjectName("obzharka")
        self.type = QtWidgets.QLineEdit(Dialog)
        self.type.setGeometry(QtCore.QRect(130, 70, 113, 20))
        self.type.setObjectName("type")
        self.descr = QtWidgets.QLineEdit(Dialog)
        self.descr.setGeometry(QtCore.QRect(130, 100, 113, 20))
        self.descr.setObjectName("descr")
        self.price = QtWidgets.QLineEdit(Dialog)
        self.price.setGeometry(QtCore.QRect(130, 130, 113, 20))
        self.price.setObjectName("price")
        self.volume = QtWidgets.QLineEdit(Dialog)
        self.volume.setGeometry(QtCore.QRect(130, 160, 113, 20))
        self.volume.setObjectName("volume")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 101, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 91, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 91, 16))
        self.label_6.setObjectName("label_6")
        self.DelBtn = QtWidgets.QPushButton(Dialog)
        self.DelBtn.setGeometry(QtCore.QRect(10, 190, 111, 121))
        self.DelBtn.setObjectName("DelBtn")
        self.ConfirmBtn = QtWidgets.QPushButton(Dialog)
        self.ConfirmBtn.setGeometry(QtCore.QRect(130, 190, 111, 121))
        self.ConfirmBtn.setObjectName("ConfirmBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Название сорта"))
        self.label_2.setText(_translate("Dialog", "Степень обжарки"))
        self.label_3.setText(_translate("Dialog", "Молотый/в зёрнах"))
        self.label_4.setText(_translate("Dialog", "Описание вкуса"))
        self.label_5.setText(_translate("Dialog", "Цена (в бублях)"))
        self.label_6.setText(_translate("Dialog", "Объём упаковки"))
        self.DelBtn.setText(_translate("Dialog", "Удалить"))
        self.ConfirmBtn.setText(_translate("Dialog", "Сохранить"))
