# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 330)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(10, 40, 781, 281))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.AddBtn = QtWidgets.QPushButton(Form)
        self.AddBtn.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.AddBtn.setObjectName("AddBtn")
        self.EditBtn = QtWidgets.QPushButton(Form)
        self.EditBtn.setGeometry(QtCore.QRect(90, 10, 75, 23))
        self.EditBtn.setObjectName("EditBtn")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(170, 15, 47, 13))
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Кофе"))
        self.AddBtn.setText(_translate("Form", "Добавить"))
        self.EditBtn.setText(_translate("Form", "Настроить"))
